services:

  telemetry-agent:
    container_name: telemetry-agent
    command:
      - python
      - main.py
    build: ./services/telemetry-agent
    env_file:
      - ./services/telemetry-agent/.env
    depends_on:
      kafka-broker:
        condition: service_healthy

  kafka-broker:
    image: apache/kafka:4.0.2
    hostname: broker
    container_name: kafka
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "broker:29092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  bronze-spark-metric-ingestion:
    container_name: bronze-spark-metric-ingestion
    build: ./services/stream-processor
    command:
      - python
      - jobs/bronze/metric_ingestion/bronze_start.py
    env_file:
      - ./services/stream-processor/.env
    depends_on:
      - telemetry-agent
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint

  silver-spark-metric-cleanup:
    container_name: silver-spark-metric-cleanup
    build: ./services/stream-processor
    command:
      - python
      - jobs/silver/silver_start.py
    env_file:
      - ./services/stream-processor/.env
    depends_on:
      - bronze-spark-metric-ingestion
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint


  gold-spark-hourly-temperature:
    container_name: gold-spark-hourly-temperature
    build: ./services/stream-processor
    command:
      - python
      - jobs/gold/temperature/hourly_temperature_start.py
    env_file:
      - ./services/stream-processor/.env
    profiles: ["manual"]
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint

  gold-spark-daily-steps-summary:
    container_name: gold-spark-daily-steps-summary
    build: ./services/stream-processor
    command:
      - python
      - jobs/gold/steps/daily_steps_start.py
    env_file:
      - ./services/stream-processor/.env
    profiles: ["manual"]
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint

  gold-spark-heart-rate-summary:
    container_name: gold-spark-heart-rate-summary
    build: ./services/stream-processor
    command:
      - python
      - jobs/gold/heart_rate/heart_rate_summary_start.py
    env_file:
      - ./services/stream-processor/.env
    profiles: ["manual"]
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint

  gold-spark-blood-pressure-summary:
    container_name: gold-spark-blood-pressure-summary
    build: ./services/stream-processor
    command:
      - python
      - jobs/gold/blood_pressure/blood_pressure_summary_start.py
    env_file:
      - ./services/stream-processor/.env
    profiles: ["manual"]
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint

  gold-spark-collecting-anomalies:
    container_name: gold-spark-collecting-anomalies
    build: ./services/stream-processor
    command:
      - python
      - jobs/gold/anomalies/collecting_anomalies_start.py
    env_file:
      - ./services/stream-processor/.env
    profiles: ["manual"]
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint

  alerting-service:
    container_name: alerting-service
    build: ./services/alerting-service
    command:
      - python
      - main.py
    env_file:
      - ./services/alerting-service/.env
    profiles: ["manual"]
    volumes:
      - /tmp/delta:/tmp/iot-streaming/delta
      - /tmp/checkpoints:/tmp/iot-streaming/checkpoint